@uuid = ""
@code = requests

### Check health
# @name checkHealth
GET http://localhost:3000/api/v1/health


### Check custom endpoint
# @name checkHealth
GET http://localhost:3000/test


### Create new process
# @name createProcess
POST http://localhost:3000/api/v1/process
Content-Type: application/json

{
    "code": "{{code}}",
    "current_status": {
        "name": "open"
    },
    "payload": {
        "sample": "payload"
    }
}

###
@uuid = {{createProcess.response.body.uuid}}


### Get p1rocess by UUID
 
GET http://localhost:3000/api/v1/process/{{code}}/{{uuid}}

### Get processes by code

GET http://localhost:3000/api/v1/process/{{code}}/list
X-Page-Size: 5
X-Page: 1


### Get processes by code - default X-Page zero 

GET http://localhost:3000/api/v1/process/{{code}}/list
X-Page: 1

### Move item of process into to status

PATCH http://localhost:3000/api/v1/process/{{code}}/{{uuid}}/assign/in_progress
Content-Type: application/json

{
    "payload": {
        "data": {
            "user_name": "alex",
            "age": 42,
            "salary": 200000.0
        }
    }
}

### Move item of process into to status

PATCH http://localhost:3000/api/v1/process/requests/{{uuid}}/assign/inprocess
