@uuid = ""

### Create new process
# @name createProcess
POST http://localhost:3000/api/v1/process
Content-Type: application/json

{
    "code": "requests",
    "metadata": {
        "sample": "metadata"
    }
}

###
@uuid = {{createProcess.response.body.uuid}}


### Get p1rocess by UUID

GET http://localhost:3000/api/v1/process/requests/{{uuid}}

### Get processes by code

GET http://localhost:3000/api/v1/process/requests/list


### Move item of process into to status

PATCH http://localhost:3000/api/v1/process/requests/{{uuid}}/assign/created
Content-Type: application/json

{
    "metadata": {
        "sample": "metadata",
        "moveit": "into created"
    }
}

### Move item of process into to status

PATCH http://localhost:3000/api/v1/process/requests/{{uuid}}/assign/inprocess
